# apiVersion: v1  (you can use this one also) first one is creating two containers in same pod ex: 2/2
# kind: Pod
# metadata:
#   name: pod-with-multiple-containers
# spec:
#   containers:
#   - name: 1st
#     image: nginx
#   - name: 2nd
#     image: debian


apiVersion: v1 # this one is creating two containers individuall  ex: 1/1 ,1/1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: container1
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: container2
      image: busybox
      command: ["sleep", "3600"]
