apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep" , "3600"]
      env:
        - name: APP
          value: ecomm 
        - name: BATCH
          value: "54"  
        - name : ENV
          value: "DEV"  


# this is how we pass the ENV variables in the kubernetes          
# What if you have 10 environment variables ?
# What if you have 10 environment variables and all of them are common to all of your 10 pods ?
# * Do you delcare them 10 times ? configMap 