# A Configmap is holder of environment variables which can be injected to any of the kubernetes resources.
# Usually values that are common across the applications will be placed in a configMap and will be used inside the pods.
# To use configMap, we would use envFrom.
# ConfigMap's are only used to handle non-sensiteve values only.
# If you want to inject userName , Password, Token, you need to use another type of resource called as secrets.

apiVersion: v1   # using this configmaps we can pass the ENV varible in mulple pod like write once use many times.
kind: ConfigMap
metadata:
  name: ecomm-configmap
data:
  #MONGODB_URL: "mongodb.roboshop.internal"
  ENV: dev
  BATCH: "54" 
  APP: ecomm 


--- 

apiVersion: v1
kind: Pod
metadata:
  name: centos-with-cm 
spec:
  containers:
  - name: centos
    image: centos:8
    command: ["sleep" , "1000"]
    envFrom:
      - configMapRef: 
          name: ecomm-configmap

--- 
apiVersion: v1
kind: Pod
metadata:
  name: centos-with-cm 
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep" , "1000"]
    envFrom:
      - configMapRef: 
          name: ecomm-configmap   