# Secrets are used to pass sensitive information.
# Secrets has to be supplied using base64 format, so that your secrets won't be in the plain text format.
# Once you inject the secret to pod, while injecting, your pod will decode it and same inside as a plain environment variable.

apiVersion: v1
kind: Secret 
metadata:
  name: ecomm-secrets
data:
  MONGODB_USERNAME: YWRtaW4K
  MONGODB_PASSWORD: bW9uZ28xMzIzNGRiCg==
  ECOMM_API_TOKEN:  YXNkZjI0ZXdmZHF3ZWZmYXhkc2FkZgo=

--- 

apiVersion: v1
kind: Pod
metadata:
  name: centos-with-secrets
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep" , "1000"]
    envFrom:
      - secretRef: 
          name: ecomm-secrets