# Limits and requests define what is the minimum and maximum cpu, memory that a pod can have.

# Requests define the Lower Cap or Minimum Resource that are needed to start a pod
# Limits define the Upper Cap or Maximum Resource that can be used by the pod. And if the pod reaches the maximum resources, then it is [kubelet] is going to restart the POD 
# Metrics can be CPO, Memory or PageSize. [ You can also create your custom metrics to define them].

# Limits and requests are at the Container Level of the Pod. Not at POD Level.

# 20% of the resources will be consumed by OS [ Internal Functions ]

# Ensure pod 100% should be less than 80% of the node size.
# If pod is not able to find the node as per it's limits and requests, POD will stay in the pending state.


apiVersion: v1
kind: Pod
metadata:
  name: resource-limit-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"


 # d         
